# Fundamentos de Aprendizaje Automático y Reconocimiento de Patrones
***
# Práctico 0

In [3]:
# Se importa la biblioteca numpy
import numpy as np

## Objetivos

Es un objetivo del plantel docente que los estudiantes adquieran ciertas habilidades de programación que le permitan implementar algoritmos de *aprendizaje automático*.  Este práctico busca brindarle al estudiante una serie de ejercicios de programación que le permitan:

- enfrentarse rápidamente a algunas tareas de programación típicas del curso
- evaluar si ya cuenta con los conocimientos necesarios para resolverlos 
- identificar qué aspectos de la programación en *python* (y su biblioteca asociada *numpy*) son más relevantes para el curso.  

### Observaciones

Los ejercicios aquí propuestos surgen a partir de la identificación de algunas de las dificultades más comunes  que enfrentaron los estudiantes de la edición anterior del curso. No se espera que todos los estudiantes sean capaces de resolver los ejercicios en la primera semana del curso. Somos conscientes que en muchos casos éste será el primer contacto con las herramientas de programación del curso. Sin embargo, consideramos **necesario** que puedan resolver este tipo de tareas  **antes** de la instancia del **primer parcial**.     

**Nota 1:** Para aquellos que no están familiarizados con Python/numpy se **recomienda fuertemente** la lectura de los siguientes tutoriales antes de realizar estos ejercicios.

- [Curso Básico de Python](https://iie.fing.edu.uy/personal/vagonbar/curso-basico-de-python/): Curso que provee una formación básica en el lenguaje de Python. Se sugiere la lectura de los primeros cinco capítulos para aquellos no familiarizados con python.
- [Python-Numpy tutorial](https://cs231n.github.io/python-numpy-tutorial/): Introducción rápida al lenguaje de programación Python, y al uso de Python para computación científica.



**Nota 2:** Los parciales y los prácticos se harán en Jupyter Notebook. Pueden encontrar una [guía de instalación](https://eva.fing.edu.uy/mod/page/view.php?id=90800) del ambiente de trabajo (miniconda) en el eva del curso. 

*** 

## Lista de ejercicios

[Ejercicio 1](#Ejercicio1): Indices en arreglos 1d y 2d    
[Ejercicio 2](#Ejercicio2): Comparación de arreglos  
[Ejercicio 3](#Ejercicio3): No es copia   
[Ejercicio 4](#Ejercicio4): Atentos al broadcasting   
[Ejercicio 5](#Ejercicio5): Sin loops por favor

<a id="Ejercicio1"></a>
### Ejercicio 1 

**Parte a)** 

Modificar la siguiente celda de forma que al ejecutarla, la salida sea la siguiente: 

```
---------------------------------------
[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[1 3 5]
[9 8 7 6]
[9 8 7 6 5 4 3 2 1 0]
---------------------------------------
```

In [4]:
print('---------------------------------------')

x = np.arange(10)
print(x)

y = np.arange(2, 5, 1)
print(y)

y = np.arange(1, 6, 2)
print(y)

y = np.arange(9, 5, -1)
print(y)

y = np.arange(9, -1, -1)
print(y)

print('---------------------------------------')

---------------------------------------
[0 1 2 3 4 5 6 7 8 9]
[2 3 4]
[1 3 5]
[9 8 7 6]
[9 8 7 6 5 4 3 2 1 0]
---------------------------------------


**Parte b)** Manipulación de arreglos

Modificar la siguiente celda de forma que al ejecutarla, la salida sea la siguiente: 

```
---------------------------------------
[[1 2 3]  
 [4 5 6]]  
[2 5]  
[[3 2 1]  
 [6 5 4]]  
---------------------------------------
```

In [10]:
print('---------------------------------------')

b = np.array([[1,2,3],[4,5,6]])
print(b)

y = b[:,1] 
print(y)

y  =b[:,::-1] 
print(y)

print('---------------------------------------')

---------------------------------------
[[1 2 3]
 [4 5 6]]
[2 5]
[[3 2 1]
 [6 5 4]]
---------------------------------------


In [1]:
def rotate(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    res = []
    for i in range(cols):
        temp = []
        for j in range(rows):
            temp.append(matrix[j][i])
        res.append(temp[::-1])

    return res


matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(rotate(matrix))

[[], [], []]


**Parte c)** Completar el código de la función `generar_marco_2d()`. 

In [4]:
def generar_marco_2d(N, M):
    '''
    Genera un arreglo 2D de dimensiones (N,M). 
    Los elementos del arreglo valen 0 salvo en los bordes donde valen 1.

    Sugerencia: no debería llevarle más de tres líneas

    Entrada:
    --------
        N: número de filas del marco
        M: número de columas del marco

    Salida:
    -------
        marco: arreglo de tamaño (N,M)
    '''
    ##########################################
    ### EMPIEZA ESPACIO PARA COMPLETAR CÓDIGO
    ##########################################
    marco=np.zeros((N,M))
    marco[-1,:]=marco[0,:]=np.ones((1,M))
    marco[:,-1]=marco[:,0]=np.ones((1,N))
    
    

    ##########################################
    ### TERMINA ESPACIO PARA COMPLETAR CÓDIGO
    ##########################################
    return marco

La siguiente celda verifica que la implementación de la generación del marco sea correcta.

In [5]:
from numpy.testing import assert_equal, assert_array_equal
# se verifica el funcionamiento con algunas muestras
assert_array_equal(generar_marco_2d(1, 1), [[1]])
assert_array_equal(generar_marco_2d(2, 2), [[1, 1], [1, 1]])
assert_array_equal(generar_marco_2d(3, 3), [[1, 1, 1], [1, 0, 1], [1, 1, 1]])
assert_array_equal(generar_marco_2d(3, 4), [[1, 1, 1, 1], [1, 0, 0, 1], [1, 1, 1, 1]])

# se verifica con algunos marcos generados aleatoriamente
for i in range(10):
    n, m = np.random.randint(2, 1000, 2)
    result = generar_marco_2d(n, m)

    # se verifica el tamaño
    assert_equal(result.shape, (n, m))

    # se verifican los bordes
    assert (result[0] == 1).all()
    assert (result[-1] == 1).all()
    assert (result[:, 0] == 1).all()
    assert (result[:, -1] == 1).all()

    # Se verifica el interior
    assert np.sum(result) == (2*n + 2*m - 4)

print("Éxito!")

Éxito!


<a id="Ejercicio2"></a>
### Ejercicio 2

La siguiente celda genera dos arreglos binarios de tamaño 10. Utilizando una línea de código, calcular la cantidad de elementos que tienen el mismo valor.  

In [6]:
a = np.random.randint(0,2,10)
b = np.random.randint(0,2,10)
print(a)
print(b)

numero_coincidencias = len(a) - np.count_nonzero(a-b)
print(numero_coincidencias)

[0 0 0 1 1 0 1 1 0 1]
[1 1 1 0 1 1 1 1 1 1]
4


<a id="Ejercicio3"></a>
### Ejercicio 3
**Parte a)**  Explicar la salida de la siguiente celda

In [7]:
a=np.array([1,2,3])
b=a.copy()
b[1]=0
print(a)
print(b)

[1 2 3]
[1 0 3]


**Parte b)**  ¿Qué sucede cuando la segunda línea se sustituye por $b=a$? ¿Cambia el comportamiento si se usa b=a.copy()?

**Respuesta:** ... Cambia si, cuando se usa copy no se modifica el array "a" cuando se setea b[1]=0, en el otro caso sí.  

<a id="Ejercicio4"></a>
### Ejercicio 4

Se considera el siguiente bloque de código

In [8]:
d=4
unos  = np.ones(d)
X = np.random.rand(d,d)
print(unos)
print(X)

[1. 1. 1. 1.]
[[0.24401289 0.69080954 0.54806445 0.72494934]
 [0.87930104 0.06901922 0.05366777 0.2119049 ]
 [0.01390756 0.49866147 0.32097849 0.63290223]
 [0.98882615 0.55657625 0.56678439 0.45826547]]


**Parte a)** Explicar qué es lo que hacen las líneas 2 y 3 de la celda

**Respuesta:** ... unos es un array de 1 de tamaño 4, mientras que X es una matrix de valores random entre 0 y 1 (sin incluir) de tamaño 4x4

**Parte b)**  Explicar la salida de la siguiente celda. En particular, observe que las dimensiones de $X$ y $unos$ no coinciden y sin embargo las operaciones no generan error.

**Respuesta:** ...

In [9]:
Y1 = X + unos
Y2 = X*unos
print(Y1)
print(Y2)

[[1.24401289 1.69080954 1.54806445 1.72494934]
 [1.87930104 1.06901922 1.05366777 1.2119049 ]
 [1.01390756 1.49866147 1.32097849 1.63290223]
 [1.98882615 1.55657625 1.56678439 1.45826547]]
[[0.24401289 0.69080954 0.54806445 0.72494934]
 [0.87930104 0.06901922 0.05366777 0.2119049 ]
 [0.01390756 0.49866147 0.32097849 0.63290223]
 [0.98882615 0.55657625 0.56678439 0.45826547]]


**Pate c)** Explique qué operación se realiza en la siguiente celda.
Es una multiplicacion matricial (producto suma). 

In [10]:
Z1 = np.dot(X, unos)
Z2 = X @ unos
print(Z1)
print(Z2)

[2.20783621 1.21389293 1.46644975 2.57045225]
[2.20783621 1.21389293 1.46644975 2.57045225]


**Parte d)** Se quiere construir una matriz X_ agregando una columna de unos antes de la primera columna de la matriz X. La siguiente celda da error. Proponga una forma de lograrlo utilizando la misma función de numpy `hstack`. Puede ser útil acceder a la documentación de las funciones dentro de los Notebooks, para ello debe colocar el cursor previo a los paréntesis de la función en cuestión y presionar **Shift+Tab** si trabaja desde Jupyter Notebooks, o **Ctrl+Space** si trabaja desde Google Colab. 

In [11]:
unos = np.ones(d) 
X_ = np.hstack((unos, X))
print(X_)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

<a id="Ejercicio5"></a>
### Ejercicio 5

Completar la función `distancia_euclidea()` que para dos vectores de entrada $\mathbf{a}$ y $\mathbf{b}$ de dimensión $d$ tiene como salida
$$
d(\mathbf{a}, \mathbf{b}) = \sqrt{\sum_{i=1}^d (a_i - b_i) ^ 2}
$$

La implementación se hará en una línea de código y deberá utilizar la función `np.sqrt()`. 

In [1]:
def distancia_euclidea(a, b):
    '''
    Calcula la distancia Euclídea entre los vectores a y b.
    
    Entrada
    ----------
    a, b : numpy arrays del mismo tamaño o escalares 
    
    Salida
    -------
    dist: distancia Euclídea entre a y b
    
    '''
    
    ##########################################
    ### EMPIEZA ESPACIO PARA COMPLETAR CÓDIGO
    ##########################################
   
    dist=np.sqrt(np.sum(np.square(a-b)))

    ##########################################
    ### TERMINA ESPACIO PARA COMPLETAR CÓDIGO
    ##########################################
    
    return dist

Pueden correr la siguiente celda para verificar si su implementación es correcta.

In [2]:
from numpy.testing import assert_equal, assert_raises

# verifica el cálculo de la distancia para arreglos de tamaño 3
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
assert_equal(distancia_euclidea(a, b), 5.196152422706632)

# verifica el cálculo de la distancia para arreglos de tamaño 4
x = np.array([3.6, 7., 203., 3.])
y = np.array([6., 20.2, 1., 2.])
assert_equal(distancia_euclidea(x, y), 202.44752406487959)

# verifica el cálculo en el caso de escalares
assert_equal(distancia_euclidea(1, 0.5), 0.5)

# verifica que haya error en el caso que los arreglos tengan distinto tamanho
a = np.array([1, 2, 3])
b = np.array([4, 5])
assert_raises(ValueError, distancia_euclidea, a, b)
assert_raises(ValueError, distancia_euclidea, b, a)

print("Éxito!")

NameError: name 'np' is not defined